### ISSUE TITLE
installation error on Mac

### ISSUE THREAD

**Issue by gurdeep101** [ericmjl/Network-Analysis-Made-Simple#325]
I'm getting the below error when installing the package via Conda. Am using MacOS Monterey  12.2.1 on 2017 MacBook Air 

ERROR conda.core.link:_execute(740): An error occurred while installing package 'conda-forge::rise-5.7.1-py39h6e9494a_2'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::rise-5.7.1-py39h6e9494a_2
location of failed script: /Users/gurdeep_working/miniconda3/envs/nams/bin/.rise-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/Users/gurdeep_working/miniconda3/envs/nams/bin/jupyter-nbextension", line 10, in <module>
    sys.exit(main())
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/traitlets/config/application.py", line 1041, in launch_instance
    app.start()
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/notebook/nbextensions.py", line 972, in start
    super().start()
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/jupyter_core/application.py", line 266, in start
    self.subapp.start()
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/notebook/nbextensions.py", line 882, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/notebook/nbextensions.py", line 855, in toggle_nbextension_python
    return toggle(module,
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/notebook/nbextensions.py", line 470, in enable_nbextension_python
    return _set_nbextension_state_python(True, module, user, sys_prefix,
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/notebook/nbextensions.py", line 368, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
    m = import_item(module)
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/traitlets/utils/importstring.py", line 38, in import_item
    return __import__(parts[0])
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/rise/__init__.py", line 3, in <module>
    __version__ = pkg_resources.require("rise")[0].version
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/gurdeep_working/miniconda3/envs/nams/lib/python3.9/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'webcolors>=1.11; extra == "format-nongpl"' distribution was not found and is required by jsonschema

return code: 1

()

**Comment by gurdeep101** [comment]
getting the same error with viscose containers on Mac

#0 390.9 ERROR conda.core.link:_execute(733): An error occurred while installing package 'conda-forge::rise-5.7.1-py39hf3d152e_2'.
#0 390.9 Rolling back transaction: ...working... done
#0 415.2 
#0 415.2 LinkError: post-link script failed for package conda-forge::rise-5.7.1-py39hf3d152e_2
#0 415.2 location of failed script: /opt/conda/bin/.rise-post-link.sh
#0 415.2 ==> script messages <==
#0 415.2 <None>
#0 415.2 ==> script output <==
#0 415.2 stdout: 
#0 415.2 stderr: Traceback (most recent call last):
#0 415.2   File "/opt/conda/bin/jupyter-nbextension", line 10, in <module>
#0 415.2     sys.exit(main())
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 277, in launch_instance
#0 415.2     return super().launch_instance(argv=argv, **kwargs)
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 1041, in launch_instance
#0 415.2     app.start()
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 972, in start
#0 415.2     super().start()
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 266, in start
#0 415.2     self.subapp.start()
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 882, in start
#0 415.2     self.toggle_nbextension_python(self.extra_args[0])
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 855, in toggle_nbextension_python
#0 415.2     return toggle(module,
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 470, in enable_nbextension_python
#0 415.2     return _set_nbextension_state_python(True, module, user, sys_prefix,
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 368, in _set_nbextension_state_python
#0 415.2     m, nbexts = _get_nbextension_metadata(module)
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 1107, in _get_nbextension_metadata
#0 415.2     m = import_item(module)
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/traitlets/utils/importstring.py", line 38, in import_item
#0 415.2     return __import__(parts[0])
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/rise/__init__.py", line 3, in <module>
#0 415.2     __version__ = pkg_resources.require("rise")[0].version
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 909, in require
#0 415.2     needed = self.resolve(parse_requirements(requirements))
#0 415.2   File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 795, in resolve
#0 415.2     raise DistributionNotFound(req, requirers)
#0 415.2 pkg_resources.DistributionNotFound: The 'webcolors>=1.11; extra == "format-nongpl"' distribution was not found and is required by jsonschema
#0 415.2 
#0 415.2 return code: 1
#0 415.2 
#0 415.2 ()
#0 415.2 
------
ERROR: failed to solve: executor failed running [/bin/sh -c apt-get update     && apt-get -y install --no-install-recommends apt-utils dialog 2>&1     && apt-get -y install git openssh-client less iproute2 procps iproute2 lsb-release     && /opt/conda/bin/pip install pylint     && if [ -f "/tmp/conda-tmp/environment.yml" ]; then /opt/conda/bin/mamba env update -n base -f /tmp/conda-tmp/environment.yml; fi     && rm -rf /tmp/conda-tmp     && groupadd --gid $USER_GID $USERNAME     && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME     && apt-get install -y sudo     && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME    && chmod 0440 /etc/sudoers.d/$USERNAME     && apt-get install -y nano vim emacs     && python -m ipykernel install --user --name "nams" --display-name "Network Analysis Made Simple"     && apt-get autoremove -y     && apt-get clean -y     && rm -rf /var/lib/apt/lists/*     ENV DEBIAN_FRONTEND=dialog]: exit code: 1
[430841 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/yg/d0p_k81s2y5_7pp0htgckbnw0000gp/T/devcontainercli/container-features/0.25.2-1672899418820/Dockerfile-with-features -t vsc-network-analysis-made-simple-c51cfef7ed9101e18fde3379e41a52b4 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/gurdeep_working/Desktop/Network-Analysis-Made-Simple
[430841 ms]     at Doe (/Users/gurdeep_working/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1894:1669)
[430841 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[430841 ms]     at async EF (/Users/gurdeep_working/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1978)
[430842 ms]     at async uT (/Users/gurdeep_working/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:901)
[430842 ms]     at async Poe (/Users/gurdeep_working/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:2128)
[430842 ms]     at async Zf (/Users/gurdeep_working/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1899:3278)
[430842 ms]     at async aue (/Users/gurdeep_working/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15276)
[430842 ms]     at async oue (/Users/gurdeep_working/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:15030)
[430858 ms] Exit code 1
[430874 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/gurdeep_working/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/gurdeep_working/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/gurdeep_working/Desktop/Network-Analysis-Made-Simple --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/gurdeep_working/Desktop/Network-Analysis-Made-Simple --log-level debug --log-format json --config /Users/gurdeep_working/Desktop/Network-Analysis-Made-Simple/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[430874 ms] Exit code 1

**Comment by ericmjl** [comment]
@gurdeep101 apologies for not responding earlier. I've switched away from conda now, and exclusively use pixi. Any chance this might work for you?
